# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-26 20:04
from __future__ import unicode_literals

import bands.helpers
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0045_multiple_professionaltags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='T\xedtulo')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (url)')),
                ('day', models.DateField(auto_now_add=True, null=True)),
                ('news_tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag de noticias')),
                ('profile_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=bands.helpers.RandomFileName('special/'), verbose_name='Imagen principal')),
                ('top_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=bands.helpers.RandomFileName('special/'), verbose_name='Imagen de cabecera')),
                ('primary_bg', models.CharField(max_length=10, verbose_name='Color de fondo principal')),
                ('primary_text', models.CharField(max_length=10, verbose_name='Color de texto principal')),
                ('secondary_bg', models.CharField(max_length=10, verbose_name='Color de fondo secundario')),
                ('secondary_text', models.CharField(max_length=10, verbose_name='Color de texto secundario')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
                ('embed_code', models.TextField(blank=True, null=True, verbose_name='C\xf3dido embed 1')),
                ('embed_media', models.TextField(blank=True, null=True, verbose_name='C\xf3dido embed 2')),
                ('events', models.ManyToManyField(blank=True, related_name='microsites', to='bands.Event', verbose_name='Eventos')),
            ],
            options={
                'ordering': ['day'],
                'verbose_name': 'Microsite especial',
                'verbose_name_plural': 'Microsites especiales',
            },
        ),
    ]
