# Generated by Django 2.2.13 on 2021-09-21 16:28

import bands.helpers
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('microsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsite',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AddField(
            model_name='microsite',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='microsite',
            name='top_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=bands.helpers.RandomFileName('special/'), verbose_name='Imagen fondo de cabecera'),
        ),
    ]
