# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-02 08:53
from __future__ import unicode_literals

import bands.models.event
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bands', '0023_auto_20170607_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Creado por'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=bands.models.event.poster_path, verbose_name=b'Imagen del evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Precio'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticketLink',
            field=models.TextField(null=True, verbose_name=b'Enlace compra de entradas'),
        ),
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
