# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-03 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0025_event_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='band',
        ),
        migrations.AddField(
            model_name='event',
            name='bands',
            field=models.ManyToManyField(to='bands.Band', verbose_name=b'Bandas'),
        ),
    ]
