# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 10:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0026_auto_20170903_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Creado por'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticketLink',
            field=models.TextField(blank=True, null=True, verbose_name=b'Enlace compra de entradas'),
        ),
    ]
