# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0027_auto_20170904_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='embed_media',
            field=models.TextField(blank=True, null=True, verbose_name='C\xf3dido embed de v\xeddeo (Youtube, Vimeo...'),
        ),
        migrations.AddField(
            model_name='band',
            name='webpage_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='P\xe1gina web'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name=b'Descripci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='band',
            name='embed_code',
            field=models.TextField(blank=True, null=True, verbose_name='C\xf3dido embed para escucha (Bandcamp, Soundcloud, Spotify...'),
        ),
        migrations.AlterField(
            model_name='band',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
