# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 12:15
from __future__ import unicode_literals

import bands.models.event
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0028_auto_20170904_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=bands.models.event.poster_path, verbose_name=b'Imagen del evento'),
        ),
    ]
