# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 12:34
from __future__ import unicode_literals

import bands.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0030_auto_20170904_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=bands.helpers.RandomFileName('venue/')),
        ),
        migrations.AlterField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
