# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0032_auto_20170905_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_preorder',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Precio preventa'),
        ),
    ]
