# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0033_event_price_preorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ticketLink',
            new_name='ticket_link',
        ),
    ]
