# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0034_auto_20170906_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='spotify_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de Spotify'),
        ),
    ]
