# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0035_band_spotify_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='public_space',
            field=models.BooleanField(default=False, verbose_name='Espacio en la v\xeda p\xfablica'),
        ),
    ]
