# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0036_venue_public_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vanue_address',
            field=models.TextField(blank=True, null=True, verbose_name=b'Direcci\xc3\xb3n del espacio'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.TextField(blank=True, null=True, verbose_name=b'Nombre del espacio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bands',
            field=models.ManyToManyField(blank=True, to='bands.Band', verbose_name=b'Bandas'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='bands.Venue'),
        ),
    ]
