# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0038_professional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalTag',
            fields=[
                ('name', models.CharField(max_length=240, verbose_name='Etiqueta')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#FFFFFFFF', max_length=10)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Etiqueta profesional',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.AddField(
            model_name='professional',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pro_tag', to='bands.ProfessionalTag', verbose_name='Categor\xeda'),
        ),
    ]
