# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0040_auto_20170913_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['day', 'time'], 'permissions': (('manage_events', 'Puede crear eventos'),), 'verbose_name': 'Concierto', 'verbose_name_plural': 'Conciertos'},
        ),
        migrations.AlterField(
            model_name='venue',
            name='latitude',
            field=models.FloatField(verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='longitude',
            field=models.FloatField(verbose_name='Longitud'),
        ),
    ]
