# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0041_auto_20170918_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['name'], 'permissions': (('manage_band', 'Puede gestionar bandas'),), 'verbose_name': 'Banda', 'verbose_name_plural': 'Bandas'},
        ),
    ]
