# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-08 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0042_auto_20170928_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='vanue_address',
            new_name='venue_address',
        ),
    ]
