# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-06 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0043_auto_20171108_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professional',
            options={'ordering': ['name'], 'permissions': (('manage_pro', 'Puede gestionar un perfil profesional'),), 'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
    ]
