# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-30 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0045_multiple_professionaltags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bands',
            field=models.ManyToManyField(blank=True, related_name='events', to='bands.Band', verbose_name=b'Bandas'),
        ),
    ]
