# Generated by Django 2.2.13 on 2021-09-14 12:04

import bands.models.event
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0046_event_band_relatedname'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de Instagram'),
        ),
        migrations.AlterField(
            model_name='band',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='band',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='band_tag', to='bands.Tag'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bands',
            field=models.ManyToManyField(blank=True, related_name='events', to='bands.Band', verbose_name='Bandas'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=bands.models.event.poster_path, verbose_name='Imagen del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_preorder',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio preventa'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_link',
            field=models.TextField(blank=True, null=True, verbose_name='Enlace compra de entradas'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Título del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue', to='bands.Venue'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección del espacio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.TextField(blank=True, null=True, verbose_name='Nombre del espacio'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='key',
            field=models.CharField(max_length=240, primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
