# Generated by Django 2.2.13 on 2021-09-14 14:15

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0047_auto_20210914_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='profile_thumb',
            field=image_cropping.fields.ImageRatioField('profile_image', '200x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='profile thumb'),
        ),
    ]
