# Generated by Django 2.2.13 on 2021-09-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0048_band_profile_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='hidden_in_catalog',
            field=models.BooleanField(default=False, help_text='Ocultar el perfil del listado, para bandas que no son de Alcala pero se crea su perfil para ciclos y festivales', verbose_name='Oculto en el listado principal'),
        ),
    ]
