# Generated by Django 4.1.13 on 2025-05-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0049_band_hidden_in_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción corta (para cartel de redes)'),
        ),
    ]
