# Generated by Django 3.2.16 on 2024-09-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=40, unique=True, verbose_name='DNI/NIE')),
                ('first_name', models.CharField(max_length=240, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=240, unique=True, verbose_name='Apellidos')),
                ('birth_date', models.DateField(blank=True, verbose_name='Fecha de nacimiento')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de contacto')),
                ('favourite_genre', models.TextField(blank=True, null=True, verbose_name='Género musical favorito')),
                ('help', models.TextField(blank=True, choices=[('comunicacion', 'Comunicación y marketing'), ('diseno', 'Diseño gráfico'), ('produccion', 'Producción de eventos'), ('fotovideo', 'Foto/vídeo'), ('administracion', 'Administración y gestión'), ('otro', 'Otros (especificar)')], null=True, verbose_name='En qué te gustaría colaborar')),
                ('help_other', models.TextField(blank=True, null=True, verbose_name='Otro tipo de colaboración')),
            ],
            options={
                'verbose_name': 'Socia',
                'verbose_name_plural': 'Socias',
                'ordering': ['last_name'],
            },
        ),
    ]
