# Generated by Django 3.2.16 on 2024-09-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, help_text='Sólo lo utilizaremos para las notificaciones de asambleas generales y avisar de eventos en los que puedas participar', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=240, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, help_text='introdúcelo si quieres que te incluyamos en el grupo de Whatsapp general de la asociación, donde os mantendremos informados del desarrollo de nuestros proyectos, y donde podrás solicitar participar en el desarrollo de actividades.', max_length=50, null=True, verbose_name='Teléfono de contacto'),
        ),
    ]
