# Generated by Django 3.2.16 on 2024-09-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20240924_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='comments_extra',
            field=models.TextField(blank=True, null=True, verbose_name='Cuéntanos lo que quieras'),
        ),
    ]
