# Generated by Django 3.2.16 on 2024-10-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_comments_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='music_connection',
            field=models.TextField(blank=True, null=True, verbose_name='Vinculación con el mundo de la música'),
        ),
    ]
