# Generated by Django 4.1.13 on 2025-05-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_music_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(help_text='Sólo lo utilizaremos para las notificaciones de asambleas generales y avisar de eventos en los que puedas participar', max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
